export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad
export EDITOR='mate -w'
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
export JAVA_HOME="`/usr/libexec/java_home`"

# vim and gnome-terminal have support for 256 colours in fedora 8 at least
# Note debian/ubuntu users need to install the ncurses-term package for this
# Note this should be set in ~/.profile for Fedora startup scripts to
# setup LS_COLORS correctly.
export TERM=xterm-256color

# Don't store duplicate adjacent items in the history
HISTCONTROL=ignoreboth





source ~/.bashrc
