"
" Personal preference .vimrc file
"
" My personally preferred version of vim is the one with the "HUGE" feature
" set, in addition to the following configure options:
"
"     ./configure --with-features=huge
"                 --enable-pythoninterp --enable-rubyinterp
"                 --enable-perlinterp --with-macarchs=x86_64
"                 --with-macsdk=10.6 --enable-multibyte
"                 --enable-cscope --prefix=/usr/local
"
" To start vim without using this .vimrc file, use:
"     vim -u NORC
"
" To start vim without loading any .vimrc or plugins, use:
"     vim -u NONE
"

" Use vim settings, rather then vi settings (much better!)
" This must be first, because it changes other options as a side effect.
set nocompatible

" Preamble -------------------------------------------------------------------- {{{

" Use pathogen to easily modify the runtime path to include all plugins under
" the ~/.vim/bundle directory
filetype off                    " force reloading *after* pathogen loaded
silent! call pathogen#helptags()
silent! call pathogen#runtime_append_all_bundles()
filetype plugin indent on       " enable detection, plugins and indenting in one step

" }}}
" Basic options --------------------------------------------------------------- {{{

set modelines=0
set updatecount=50 "write swap file to disk after 50 keystrokes
set scrolljump=5
set scrolloff=4                 " keep 4 lines off the edges of the screen when scrolling
set autoindent " always set autoindenting on
set copyindent    " copy the previous indentation on autoindenting
set showmode                    " always show what mode we're currently editing in
set whichwrap=b,s,h,l,<,>,[,]
set backspace=indent,eol,start    " allow backspacing over everything in insert mode
set relativenumber
set cpoptions+=J
set listchars=tab:▸\ ,eol:¬
set shell=/bin/bash
set showbreak=↪
set splitbelow
set splitright
set ignorecase    " ignore case when searching
set smartcase     " ignore case if search pattern is all lowercase,
                  "    case-sensitive otherwise

set nrformats=octal,hex,alpha " Enable CTRL-A/CTRL-X to work on octal and hex numbers, as well as characters
set smarttab      " insert tabs on the start of a line according to
                  "    shiftwidth, not tabstop
set incsearch     " show search matches as you type                 
set showmatch     " when a bracket is inserted, breifly jump to a matching one
set matchtime=2   " jump to matching bracket for 2/10th of a second
set hlsearch      " highlight search terms
set gdefault                    " search/replace "globally" (on a line) by default
set nolist                      " don't show invisible characters by default,
                                " but it is enabled for some file types (see later)
set virtualedit=all             " allow the cursor to go in to "invalid" places

" Remember things between sessions
"
" '20  - remember marks for 20 previous files
" \"50 - save 50 lines for each register
" :20  - remember 20 items in command-line history 
" %    - remember the buffer list (if vim started without a file arg)
" n    - set name of viminfo file
set viminfo='20,\"50,:20,%,n~/.viminfo

" Editor layout {{{

set termencoding=utf-8
set encoding=utf-8
set lazyredraw                  " don't update the display while executing macros
set cmdheight=1                 " use a status bar that is 2 rows high

" }}}
" Tabs, spaces, wrapping {{{

set tabstop=4
set shiftwidth=4 " number of spaces to use for autoindenting
set shiftround    " use multiple of shiftwidth when indenting with '<' and '>'
set softtabstop=4
set expandtab                   " expand tabs by default (overloadable per file type later)
set nowrap                      " don't wrap lines
set textwidth=79
set formatoptions+=1            " When wrapping paragraphs, don't end lines
                                "    with 1-letter words (looks stupid)
" set colorcolumn=+1

" }}}
" Par {{{

"set formatprg=par\ -w78
":map <A-q> {v}!par -jw78<CR>
":vmap <A-q> !par -jw78<CR>

" }}}
" Vim behaviour {{{
set hidden                      " hide buffers instead of closing them this
                                "    means that the current buffer can be put
                                "    to background without being written; and
                                "    that marks and undo history are preserved
set switchbuf=useopen           " reveal already opened files from the
                                " quickfix window instead of opening new
                                " buffers
set history=1000                " remember more commands and search history
set undolevels=1000             " use many muchos levels of undo
set undoreload=10000
if v:version >= 730
    set undofile                " keep a persistent backup file
    set undodir=~/.vim/tmp/undo//     " undo files
endif
set nobackup                    " do not keep backup files, it's 70's style cluttering
set noswapfile                  " do not write annoying intermediate swap files,
                                "    who did ever restore from swap files anyway?
set backupdir=~/.vim/tmp/backup// " backups
set directory=~/vim/tmp/swap//   " swap files
                                " store swap files in one of these directories
                                "    (in case swapfile is ever turned on)
set wildmenu                    " make tab completion for files/buffers act like bash
set wildmode=list:longest,full  " show a list when pressing tab and complete
                                "    first full match
set wildignore=*.swp,*.bak,*.pyc,*.class
set title                       " change the terminal's title
set visualbell                  " don't beep
set noerrorbells                " don't beep
set nomodeline                  " disable mode lines (security measure)
"set ttyfast                     " always use a fast terminal
set cursorline                  " underline the current line, for quick orientation

if has('cmdline_info')
  set ruler                   " show the ruler
  set rulerformat=%30(%=\:b%n%y%m%r%w\ %l,%c%V\ %P%) " a ruler on steroids
  set showcmd                   " show (partial) command in the last line of the screen
                                "    this also shows visual selection info
endif


" }}}    
" Status line {{{

if has('statusline')
  set laststatus=2                " tell VIM to always put a status line in, even
                                "    if there is only one window
  "set statusline=\ \ \ \ \ line:%l\ column:%c\ \ \ %M%Y%r%=%-14.(%t%)\ %p%%
  set statusline=   " clear the statusline, allow for rearranging parts
  set statusline+=%f\                "Path to the file, as typed or relative to current dir
  set statusline+=%#errormsg#        "change color
  set statusline+=%{&ff!='unix'?'['.&ff.']':''}   "display a warning if fileformat isnt unix
  set statusline+=%*                "reset color to normal statusline color
  set statusline+=%#errormsg#       "change color
  set statusline+=%{(&fenc!='utf-8'&&&fenc!='')?'['.&fenc.']':''}   "display a warning if file encoding isnt utf-8
  set statusline+=%*                "reset color to normal statusline color
  set statusline+=\ %y              "filetype
  set statusline+=%([%R%M]%)        "read-only (RO), modified (+) and unmodifiable (-) flags between braces
  set statusline+=%{'~'[&pm=='']}   "shows a '~' if in patchmode
  set statusline+=\ %{fugitive#statusline()}  "show Git info, via fugitive.git
  "set statusline+=\ (%{synIDattr(synID(line('.'),col('.'),0),'name')}) "DEBUG : display the current syntax item name
  set statusline+=%#error#          "change color
  set statusline+=%{&paste?'[paste]':''}    "display a warning if &paste is set
  set statusline+=%*                "reset color to normal statusline color
  set statusline+=%=                "right-align following items
  set statusline+=#%n               "buffer number
  set statusline+=\ %l/%L,          "current line number/total number of lines,
  set statusline+=%c                "Column number
  set statusline+=%V                " -{Virtual column number} (Not displayed if equal to 'c')
  set statusline+=\ %p%%            "percentage of lines through the file%
  set statusline+=\                 "trailing space
  if has('title')
    set titlestring=%t%(\ [%R%M]%)
  endif
endif
                                
" }}}
" Leader {{{

" Change the mapleader from \ to ,
let mapleader=","

" }}}
" Color scheme {{{

if &t_Co >= 256 || has("gui_running")
  set background=dark
  "colorscheme baycomb
  colorscheme mustang
  "colorscheme molokai
  "let g:solarized_termcolors=256
  "let g:solarized_bold = 1
  "let g:solarized_underline = 1
  "let g:solarized_italic = 1
  "colorscheme solarized
endif

if &t_Co > 2 || has("gui_running")
  syntax on                    " switch syntax highlighting on, when the terminal has colors
endif  

" }}}

" }}}
" Useful abbreviations -------------------------------------------------------- {{{

" }}}
" Searching and movement ------------------------------------------------------ {{{

"clearing highlighted search
noremap <silent> <leader>/ :nohlsearch<CR>

" Change Working Directory to that of the current file
cmap cwd lcd %:p:h
cmap cd. lcd %:p:h

" Thanks to Steve Losh for this liberating tip
" See http://stevelosh.com/blog/2010/09/coming-home-to-vim
nnoremap / /\v

" Speed up scrolling of the viewport slightly
nnoremap <C-e> 2<C-e>
nnoremap <C-y> 2<C-y>

" }}}
" Directional Keys {{{

nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>  

" Easier moving in tabs and windows
noremap <C-j>  <C-w>j
noremap <C-k>  <C-w>k
noremap <C-l>  <C-w>l
noremap <C-h>  <C-w>h

" Fix home and end keybindings for screen, particularly on mac
" - for some reason this fixes the arrow keys too. huh.
" map [F $
" imap [F $
" map [H g0
" imap [H g0

" }}}
" Convenience mappings -------------------------------------------------------- {{{

" save changes
map <leader>s :w<CR>
" exit vim without saving any changes
map <leader>q :q!<CR>
" use CTRL-F for omni completion
imap <C-F> 
" map <Alt-p> and <Alt-P> to paste below/above and reformat
nnoremap <M-P> P'[v']=
nnoremap <M-p> p'[v']=

" Clean whitespace
map <leader>W :%s/\s\+$//<cr>:let @/=''<CR>

" Yankring
nnoremap <silent> <F6> :YRShow<cr>
let g:yankring_history_dir = '~/.vim/tmp'

" Formatting, TextMate-style
nnoremap <leader>q gqip

" Easier linewise reselection
nnoremap <leader>v V`]

" Better Completion
set completeopt=longest,menuone,preview

" This is a little tweak that is a time-saver while you’re building
" up your .vimrc. This effectively maps the ,ev and ,sv keys to
" edit/reload .vimrc. (I got this from Derek Wyatt’s .vimrc file.)
nmap <silent> <leader>ev :e $MYVIMRC<CR>
nmap <silent> <leader>sv :so $MYVIMRC<CR>

" Sudo to write
cmap w!! w !sudo tee % >/dev/null

" Quickly close the current window
"nnoremap <leader>q :q<CR>

" Use Q for formatting the current paragraph (or visual selection)
"vmap Q gq
"nmap Q gqap

" Use ,d (or ,dd or ,dj or 20,dd) to delete a line without adding it to the
" yanked stack (also, in visual mode)
nmap <silent> <leader>d "_d
vmap <silent> <leader>d "_d  

" Yank from the cursor to the end of the line, to be consistent with C and D.
nnoremap Y y$
nnoremap D d$

" Yank/paste to the OS clipboard with ,y and ,p
nmap <leader>y "+y
nmap <leader>Y "+yy
nmap <leader>p "+p   
nmap <leader>P "+P   

" visual shifting (does not exit Visual mode)
vnoremap < <gv
vnoremap > >gv

" Quick alignment of text
nmap <leader>al :left<CR>
nmap <leader>ar :right<CR>
nmap <leader>ac :center<CR>

" Pull word under cursor into LHS of a substitute (for quick search and
" replace)
nmap <leader>z :%s#\<<C-r>=expand("<cword>")<CR>\>#

" Scratch
nmap <leader><tab> :Sscratch<CR><C-W>x<C-J>  

" Toggle paste: Every Vim user likes to enable auto-indenting of
" source code, so Vim can intelligently position you cursor on the
" next line as you type. This has one big ugly consequence however:
" when you paste text into your terminal-based Vim with a right
" mouse click, Vim cannot know it is coming from a paste. To Vim, it
" looks like text entered by someone who can type incredibly fast
" :) Since Vim thinks this is regular key strokes, it applies all
" auto-indenting and auto-expansion of defined abbreviations to the
" input, resulting in often cascading indents of paragraphs. There is
" an easy option to prevent this, however. You can temporarily switch
" to “paste mode”, simply by setting the following option:
set pastetoggle=<F8>

" Reselect text that was just pasted with <leader>v
nnoremap <leader>v V`]  

" Replaste
nnoremap <D-p> "_ddPV`]

" }}}
" Folding --------------------------------------------------------------------- {{{

set foldenable                  " enable folding
set foldcolumn=0                " add a fold column
set foldmethod=marker           " detect triple-{ style fold markers
set foldlevelstart=99           " start out with nothing folded
set foldopen=block,hor,insert,jump,mark,percent,quickfix,search,tag,undo
                                " which commands trigger auto-unfold
" Space to toggle folds.
nnoremap <Space> za
vnoremap <Space> za

" Make zO recursively open whatever top level fold we're in, no matter where the
" cursor happens to be.
nnoremap zO zCzO

"function! MyFoldText()
  "let line = getline(v:foldstart)

  "let nucolwidth = &fdc + &number * &numberwidth
  "let windowwidth = winwidth(0) - nucolwidth - 3
  "let foldedlinecount = v:foldend - v:foldstart

  "" expand tabs into spaces
  "let onetab = strpart('          ', 0, &tabstop)
  "let line = substitute(line, '\t', onetab, 'g')

  "let line = strpart(line, 0, windowwidth - 2 -len(foldedlinecount))
  "let fillcharcount = windowwidth - len(line) - len(foldedlinecount) - 4
  "return line . ' …' . repeat(" ",fillcharcount) . foldedlinecount . ' '
"endfunction
"set foldtext=MyFoldText()

""" Code folding options
nmap <leader>f0 :set foldlevel=0<CR>
nmap <leader>f1 :set foldlevel=1<CR>
nmap <leader>f2 :set foldlevel=2<CR>
nmap <leader>f3 :set foldlevel=3<CR>
nmap <leader>f4 :set foldlevel=4<CR>
nmap <leader>f5 :set foldlevel=5<CR>
nmap <leader>f6 :set foldlevel=6<CR>
nmap <leader>f7 :set foldlevel=7<CR>
nmap <leader>f8 :set foldlevel=8<CR>
nmap <leader>f9 :set foldlevel=9<CR>  

" }}}
" Destroy infuriating keys ---------------------------------------------------- {{{

" Fuck you, help key.
set fuoptions=maxvert,maxhorz
noremap <F1> :set invfullscreen<CR>
inoremap <F1> <ESC>:set invfullscreen<CR>a

" Fuck you too, manual key.
nnoremap K <nop>

" Stop it, hash key.
inoremap # X<BS>#

" }}}
" Various filetype-specific stuff --------------------------------------------- {{{

" Python {{{

" (tab width 4 chr, wrap at 79th char)
autocmd FileType python setlocal sw=4
autocmd FileType python setlocal ts=4
autocmd FileType python setlocal sts=4
autocmd FileType python setlocal textwidth=79
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete

" }}}
" Ruby {{{

"au FileType ruby setlocal expandtab shiftwidth=2 tabstop=2 softtabstop=2

" }}}
" C {{{

au FileType c setlocal foldmethod=syntax

" }}}
" HTML and HTMLDjango {{{
  
" HTML (tab width 2 chr, no wrapping)
autocmd FileType html setlocal sw=2
autocmd FileType html setlocal ts=2
autocmd FileType html setlocal sts=2
autocmd FileType html setlocal textwidth=0
autocmd FileType html setlocal omnifunc=htmlcomplete#CompleteTags

" XHTML (tab width 2 chr, no wrapping)
autocmd FileType xhtml setlocal sw=2
autocmd FileType xhtml setlocal ts=2
autocmd FileType xhtml setlocal sts=2
autocmd FileType xhtml setlocal textwidth=0

 " This function detects, based on HTML content, whether this is a
" Django template, or a plain HTML file, and sets filetype accordingly
fun! s:DetectHTMLVariant()
  let n = 1
  while n < 50 && n < line("$")
    " check for django
    if getline(n) =~ '{%\s*\(extends\|load\|block\|if\|for\|include\|trans\)\>'
      set ft=htmldjango.html
      return
    endif
    let n = n + 1
  endwhile
  " go with html
  set ft=html
endfun

"au BufNewFile,BufRead *.html,*.htm call s:DetectHTMLVariant()
" au BufNewFile,BufRead *.html setlocal filetype=htmldjango

" Auto-closing of HTML/XML tags
let g:closetag_default_xml=1
au FileType html let b:closetag_html_style=1
au FileType html,xml set listchars-=tab:>.          

"au BufNewFile,BufRead *.html setlocal foldmethod=manual

" Use <localleader>f to fold the current tag.
"au BufNewFile,BufRead *.html nnoremap <buffer> <localleader>f Vatzf
"au BufNewFile,BufRead *.html nnoremap <buffer> VV vatV
"au BufNewFile,BufRead *.htm nnoremap <buffer> <localleader>f Vatzf
"au BufNewFile,BufRead *.htm nnoremap <buffer> VV vatV

" Use Shift-Return to turn this:
"     <tag>|</tag>
"
" into this:
"     <tag>
"         |
"     </tag>
"au BufNewFile,BufRead *.html inoremap <buffer> <s-cr> <cr><esc>kA<cr>
"au BufNewFile,BufRead *.html nnoremap <buffer> <s-cr> vit<esc>a<cr><esc>vito<esc>i<cr><esc>

" }}}
" CSS and LessCSS {{{

" (tab width 2 chr, wrap at 79th char)
autocmd FileType css setlocal sw=2
autocmd FileType css setlocal ts=2
autocmd FileType css setlocal sts=2
autocmd FileType css setlocal textwidth=0
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS

au BufNewFile,BufRead *.less setlocal filetype=less

au BufNewFile,BufRead *.css  setlocal foldmethod=marker
au BufNewFile,BufRead *.less setlocal foldmethod=marker

au BufNewFile,BufRead *.css  setlocal foldmarker={,}
au BufNewFile,BufRead *.less setlocal foldmarker={,}

" Use cc to change lines without borking the indentation.
"au BufNewFile,BufRead *.css  nnoremap <buffer> cc ddko
"au BufNewFile,BufRead *.less nnoremap <buffer> cc ddko

" Use <leader>S to sort properties.  Turns this:
"
"     p {
"         width: 200px;
"         height: 100px;
"         background: red;
"
"         ...
"     }
"
" into this:

"     p {
"         background: red;
"         height: 100px;
"         width: 200px;
"
"         ...
"     }
"
"au BufNewFile,BufRead *.css  nnoremap <buffer> <localleader>S ?{<CR>jV/\v^\s*\}?$<CR>k:sort<CR>:noh<CR>
"au BufNewFile,BufRead *.less nnoremap <buffer> <localleader>S ?{<CR>jV/\v^\s*\}?$<CR>k:sort<CR>:noh<CR>

" Make {<cr> insert a pair of brackets in such a way that the cursor is correctly
" positioned inside of them AND the following code doesn't get unfolded.
"au BufNewFile,BufRead *.css  inoremap <buffer> {<cr> {}<left><cr>.<cr><esc>kA<bs><space><space>
"au BufNewFile,BufRead *.less inoremap <buffer> {<cr> {}<left><cr>.<cr><esc>kA<bs><space><space>

" }}}
" Javascript {{{

" (tab width 2 chr, no-wrapping)
autocmd FileType javascript setlocal sw=2
autocmd FileType javascript setlocal ts=2
autocmd FileType javascript setlocal sts=2
autocmd FileType javascript setlocal textwidth=0
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS

au FileType javascript setlocal listchars=trail:·,extends:#,nbsp:·
"au FileType javascript setlocal foldmethod=marker foldmarker={,}   

au FileType javascript call JavaScriptFold()
au FileType javascript setl fen
au FileType javascript setl nocindent

au FileType javascript imap <C-t> console.log();<esc>hi
au FileType javascript imap <C-a> alert();<esc>hi

function! JavaScriptFold()
    setl foldmethod=syntax
    setl foldlevelstart=1
    syn region foldBraces start=/{/ end=/}/ transparent fold keepend extend

    function! FoldText()
        return substitute(getline(v:foldstart), '{.*', '{...}', '')
    endfunction
    setl foldtext=FoldText()
endfunction

" }}}
" Markdown {{{

au BufNewFile,BufRead *.m*down setlocal filetype=markdown

" Use <localleader>1/2/3 to add headings.
au Filetype markdown nnoremap <buffer> <localleader>1 yypVr=
au Filetype markdown nnoremap <buffer> <localleader>2 yypVr-
au Filetype markdown nnoremap <buffer> <localleader>3 I### <ESC>

" }}}
" Vim {{{

au FileType vim setlocal foldmethod=marker
au FileType help setlocal textwidth=78
 " Bind <F1> to show the keyword under cursor
" general help can still be entered manually, with :h
au FileType vim noremap <buffer> <F1> <Esc>:help <C-r><C-w><CR>
au FileType vim noremap! <buffer> <F1> <Esc>:help <C-r><C-w><CR>  

" }}}
" Firefox {{{

au BufRead,BufNewFile ~/Library/Caches/* setlocal buftype=nofile

" }}}

" }}}
" Plugin settings ------------------------------------------------------------- {{{

" Ack {{{

" map <leader>a :Ack! 

" }}}
" NERD Tree {{{

" Put focus to the NERD Tree with F3 (tricked by quickly closing it and
" immediately showing it again, since there is no :NERDTreeFocus command)
nmap <leader>n :NERDTreeClose<CR>:NERDTreeToggle<CR>
nmap <leader>m :NERDTreeClose<CR>:NERDTreeFind<CR>
nmap <leader>N :NERDTreeClose<CR>
"map <F2> :NERDTreeToggle<CR>:NERDTreeMirror<CR>

let NERDTreeChDirMode=0

" Store the bookmarks file
let NERDTreeBookmarksFile=expand("~/.vim/tmp/NERDTreeBookmarks")

" Show the bookmarks table on startup
let NERDTreeShowBookmarks=1

" Show hidden files, too
let NERDTreeShowFiles=1
let NERDTreeShowHidden=1

" Quit on opening files from the tree
let NERDTreeQuitOnOpen=1

" Highlight the selected entry in the tree
let NERDTreeHighlightCursorline=1

" Use a single click to fold/unfold directories and a double click to open
" files
let NERDTreeMouseMode=2

let NERDTreeKeepTreeInNewTab=1

" Don't display these kinds of files
let NERDTreeIgnore=[ '\.pyc$', '\.pyo$', '\.py\$class$', '\.obj$', '\.o$', '\.so$', '\.egg$', '^\.git$' ]
 
" }}}
" HTML5 {{{

let g:event_handler_attributes_complete = 0
let g:rdfa_attributes_complete = 0
let g:microdata_attributes_complete = 0
let g:atia_attributes_complete = 0

" }}}
" Syntastic {{{

let g:syntastic_enable_signs=1
let g:syntastic_disabled_filetypes = ['html', 'python']

" }}}
" Delimitmate {{{

au FileType * let b:delimitMate_autoclose = 1
" If using html auto complete (complete closing tag)
au FileType xml,html,xhtml let b:delimitMate_matchpairs = "(:),[:],{:}"

" }}}
" SnipMate {{{

" Shortcut for reloading snippets, useful when developing
nnoremap ,smr <esc>:exec ReloadAllSnippets()<cr>    

" }}}
" ShowMarks {{{

let showmarks_include = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
" Don't leave on by default, use :ShowMarksOn to enable
let g:showmarks_enable = 0
" For marks a-z
highlight ShowMarksHLl gui=bold guibg=LightBlue guifg=Blue
" For marks A-Z
highlight ShowMarksHLu gui=bold guibg=LightRed guifg=DarkRed
" For all other marks
highlight ShowMarksHLo gui=bold guibg=LightYellow guifg=DarkYellow
" For multiple marks on the same line.
highlight ShowMarksHLm gui=bold guibg=LightGreen guifg=DarkGreen

" }}}
" Ctags Variables {{{

" This will look in the current directory for 'tags', and work up the tree towards root until one is found. 
set tags=./tags;/,$HOME/vimtags
" C-\ - Open the definition in a new tab
map <C-\> :tab split<CR>:exec("tag ".expand("<cword>"))<CR> 
" A-] - Open the definition in a vertical split
map <A-]> :vsp <CR>:exec("tag ".expand("<cword>"))<CR>      

" }}}
" Taglist Variables {{{

nmap <leader>l :TlistClose<CR>:TlistToggle<CR>
nmap <leader>L :TlistClose<CR>

" quit Vim when the TagList window is the last open window
let Tlist_Exit_OnlyWindow=1         " quit when TagList is the last open window
let Tlist_GainFocus_On_ToggleOpen=1 " put focus on the TagList window when it opens
"let Tlist_Process_File_Always=1     " process files in the background, even when the TagList window isn't open
"let Tlist_Show_One_File=1           " only show tags from the current buffer, not all open buffers
let Tlist_Inc_Winwidth=1            " increase window by 1 when growing

" shorten the time it takes to highlight the current tag (default is 4 secs)
" note that this setting influences Vim's behaviour when saving swap files,
" but we have already turned off swap files (earlier)
"set updatetime=1000

" the default ctags in /usr/bin on the Mac is GNU ctags, so change it to the
" exuberant ctags version in /usr/local/bin
let Tlist_Ctags_Cmd = '/usr/local/bin/ctags'

let Tlist_Enable_Fold_Column=0 
" show function/method prototypes in the list
let Tlist_Display_Prototype=1

" don't show scope info
let Tlist_Display_Tag_Scope=0

" show TagList window on the right
let Tlist_Use_Right_Window=1  

let Tlist_Auto_Highlight_Tag = 1
let Tlist_Auto_Update = 1
let Tlist_File_Fold_Auto_Close = 1
let Tlist_Use_SingleClick = 1

let g:ctags_statusline=1
" Override how taglist does javascript
let g:tlist_javascript_settings = 'javascript;f:function;c:class;m:method;p:property;v:global'  

" }}}
" JSON {{{

nmap <leader>jt <Esc>:%!python -m json.tool<CR><Esc>:set filetype=json<CR>                       

" }}}
" Easymotion {{{

let g:EasyMotion_do_mapping = 0

nnoremap <silent> <Leader>f      :call EasyMotionF(0, 0)<CR>
vnoremap <silent> <Leader>f :<C-U>call EasyMotionF(1, 0)<CR>

nnoremap <silent> <Leader>F      :call EasyMotionF(0, 1)<CR>
vnoremap <silent> <Leader>F :<C-U>call EasyMotionF(1, 1)<CR>

"}}}
" Autoclose {{{

nmap <Leader>x <Plug>ToggleAutoCloseMappings

" }}}
" Scratch {{{

command! ScratchToggle call ScratchToggle()
function! ScratchToggle() " {{{
  if exists("w:is_scratch_window")
    unlet w:is_scratch_window
    exec "q"
  else
    exec "normal! :Sscratch\<cr>\<C-W>J:resize 13\<cr>"
    let w:is_scratch_window = 1
  endif
endfunction " }}}
nnoremap <silent> <leader><tab> :ScratchToggle<cr>

" }}}
" OrgMode {{{
let g:org_plugins = ['ShowHide', '|', 'Navigator', 'EditStructure', '|', 'Todo', 'Misc']

let g:org_todo_keywords = ['TODO', 'HOLD', '|', 'DONE']
let g:org_debug = 1

" }}}

" }}}
" Synstack -------------------------------------------------------------------- {{{

" Show the stack of syntax hilighting classes affecting whatever is under the
" cursor.
function! SynStack() " {{{
  if !exists("*synstack")
    return
  endif

  echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endfunc " }}}

nmap <M-S> :call SynStack()<CR>

" }}}
" Text objects ---------------------------------------------------------------- {{{

" Shortcut for [] {{{

"onoremap id i[
"onoremap ad a[
"vnoremap id i[
"vnoremap ad a[

" }}}
" Next/Last () {{{
"vnoremap <silent> inb :<C-U>normal! f(vib<cr>
"onoremap <silent> inb :<C-U>normal! f(vib<cr>
"vnoremap <silent> anb :<C-U>normal! f(vab<cr>
"onoremap <silent> anb :<C-U>normal! f(vab<cr>
"vnoremap <silent> in( :<C-U>normal! f(vi(<cr>
"onoremap <silent> in( :<C-U>normal! f(vi(<cr>
"vnoremap <silent> an( :<C-U>normal! f(va(<cr>
"onoremap <silent> an( :<C-U>normal! f(va(<cr>

"vnoremap <silent> ilb :<C-U>normal! F)vib<cr>
"onoremap <silent> ilb :<C-U>normal! F)vib<cr>
"vnoremap <silent> alb :<C-U>normal! F)vab<cr>
"onoremap <silent> alb :<C-U>normal! F)vab<cr>
"vnoremap <silent> il( :<C-U>normal! F)vi(<cr>
"onoremap <silent> il( :<C-U>normal! F)vi(<cr>
"vnoremap <silent> al( :<C-U>normal! F)va(<cr>
"onoremap <silent> al( :<C-U>normal! F)va(<cr>
" }}}
" Next/Last {} {{{
"vnoremap <silent> inB :<C-U>normal! f{viB<cr>
"onoremap <silent> inB :<C-U>normal! f{viB<cr>
"vnoremap <silent> anB :<C-U>normal! f{vaB<cr>
"onoremap <silent> anB :<C-U>normal! f{vaB<cr>
"vnoremap <silent> in{ :<C-U>normal! f{vi{<cr>
"onoremap <silent> in{ :<C-U>normal! f{vi{<cr>
"vnoremap <silent> an{ :<C-U>normal! f{va{<cr>
"onoremap <silent> an{ :<C-U>normal! f{va{<cr>

"vnoremap <silent> ilB :<C-U>normal! F}viB<cr>
"onoremap <silent> ilB :<C-U>normal! F}viB<cr>
"vnoremap <silent> alB :<C-U>normal! F}vaB<cr>
"onoremap <silent> alB :<C-U>normal! F}vaB<cr>
"vnoremap <silent> il{ :<C-U>normal! F}vi{<cr>
"onoremap <silent> il{ :<C-U>normal! F}vi{<cr>
"vnoremap <silent> al{ :<C-U>normal! F}va{<cr>
"onoremap <silent> al{ :<C-U>normal! F}va{<cr>
" }}}
" Next/Last [] {{{
"vnoremap <silent> ind :<C-U>normal! f[vi[<cr>
"onoremap <silent> ind :<C-U>normal! f[vi[<cr>
"vnoremap <silent> and :<C-U>normal! f[va[<cr>
"onoremap <silent> and :<C-U>normal! f[va[<cr>
"vnoremap <silent> in[ :<C-U>normal! f[vi[<cr>
"onoremap <silent> in[ :<C-U>normal! f[vi[<cr>
"vnoremap <silent> an[ :<C-U>normal! f[va[<cr>
"onoremap <silent> an[ :<C-U>normal! f[va[<cr>

"vnoremap <silent> ild :<C-U>normal! F]vi[<cr>
"onoremap <silent> ild :<C-U>normal! F]vi[<cr>
"vnoremap <silent> ald :<C-U>normal! F]va[<cr>
"onoremap <silent> ald :<C-U>normal! F]va[<cr>
"vnoremap <silent> il[ :<C-U>normal! F]vi[<cr>
"onoremap <silent> il[ :<C-U>normal! F]vi[<cr>
"vnoremap <silent> al[ :<C-U>normal! F]va[<cr>
"onoremap <silent> al[ :<C-U>normal! F]va[<cr>
"" }}}
" Next/Last <> {{{
"vnoremap <silent> in< :<C-U>normal! f<vi<<cr>
"onoremap <silent> in< :<C-U>normal! f<vi<<cr>
"vnoremap <silent> an< :<C-U>normal! f<va<<cr>
"onoremap <silent> an< :<C-U>normal! f<va<<cr>

"vnoremap <silent> il< :<C-U>normal! f>vi<<cr>
"onoremap <silent> il< :<C-U>normal! f>vi<<cr>
"vnoremap <silent> al< :<C-U>normal! f>va<<cr>
"onoremap <silent> al< :<C-U>normal! f>va<<cr>
" }}}
" Next '' {{{
"vnoremap <silent> in' :<C-U>normal! f'vi'<cr>
"onoremap <silent> in' :<C-U>normal! f'vi'<cr>
"vnoremap <silent> an' :<C-U>normal! f'va'<cr>
"onoremap <silent> an' :<C-U>normal! f'va'<cr>

"vnoremap <silent> il' :<C-U>normal! F'vi'<cr>
"onoremap <silent> il' :<C-U>normal! F'vi'<cr>
"vnoremap <silent> al' :<C-U>normal! F'va'<cr>
"onoremap <silent> al' :<C-U>normal! F'va'<cr>
" }}}
" Next "" {{{
"vnoremap <silent> in" :<C-U>normal! f"vi"<cr>
"onoremap <silent> in" :<C-U>normal! f"vi"<cr>
"vnoremap <silent> an" :<C-U>normal! f"va"<cr>
"onoremap <silent> an" :<C-U>normal! f"va"<cr>

"vnoremap <silent> il" :<C-U>normal! F"vi"<cr>
"onoremap <silent> il" :<C-U>normal! F"vi"<cr>
"vnoremap <silent> al" :<C-U>normal! F"va"<cr>
"onoremap <silent> al" :<C-U>normal! F"va"<cr>
" }}}

" }}}
" Quickreturn ----------------------------------------------------------------- {{{

inoremap <c-cr> <esc>A<cr>
inoremap <s-cr> <esc>A:<cr>

" }}}
" Error toggles --------------------------------------------------------------- {{{

" Tame the quickfix window (open/close using f4)
nmap <silent> <f4> :QFix<CR>

command! -bang -nargs=? QFix call QFixToggle(<bang>0)
function! QFixToggle(forced)
  if exists("g:qfix_win") && a:forced == 0
    cclose
    unlet g:qfix_win
  else
    copen 10
    let g:qfix_win = bufnr("$")
  endif
endfunction

" }}}
" Persistent echo ------------------------------------------------------------- {{{

" http://vim.wikia.com/wiki/Make_echo_seen_when_it_would_otherwise_disappear_and_go_unseen
"
" further improvement in restoration of the &updatetime. To make this
" usable in the plugins, we want it to be safe for the case when
" two plugins use same this same technique. Two independent
" restorations of &ut can run in unpredictable sequence. In order to
" make it safe, we add additional check in &ut restoration.
let s:Pecho=''
fu! s:Pecho(msg)
  let s:hold_ut=&ut | if &ut>1|let &ut=1|en
  let s:Pecho=a:msg
  aug Pecho
    au CursorHold * if s:Pecho!=''|echo s:Pecho
          \|let s:Pecho=''|if s:hold_ut > &ut |let &ut=s:hold_ut|en|en
          \|aug Pecho|exe 'au!'|aug END|aug! Pecho
  aug END
endf

" }}}
" Open quoted ----------------------------------------------------------------- {{{

nnoremap <silent> ø :OpenQuoted<cr>
command! OpenQuoted call OpenQuoted()

" Open the file in the current (or next) set of quotes.
function! OpenQuoted() " {{{
    let @r = ''

    exe 'normal! vi' . "'" . '"ry'

    if len(@r) == 0
        exe 'normal! i' . '"' . '"ry'
    endif

    if len(@r) == 0
        exe 'normal! "ry'
        let @r = ''
    endif

    exe "silent !open ." . @r
endfunction " }}}


" Restore cursor position upon reopening files {{{
autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif
" }}}

" Common abbreviations / misspellings {{{
source ~/.vim/autocorrect.vim
" }}}

" Extra vi-compatibility {{{
" set extra vi-compatible options
set cpoptions+=$     " when changing a line, don't redisplay, but put a '$' at
                     " the end during the change
set formatoptions-=o " don't start new lines w/ comment leader on pressing 'o'
au filetype vim set formatoptions-=o
                     " somehow, during vim filetype detection, this gets set
                     " for vim files, so explicitly unset it again
" }}}

" Extra user or machine specific settings {{{
source ~/.user.vim
" }}}

" Creating underline/overline headings for markup languages
" Inspired by http://sphinx.pocoo.org/rest.html#sections
nnoremap <leader>1 yyPVr=jyypVr=
nnoremap <leader>2 yyPVr*jyypVr*
nnoremap <leader>3 yypVr=
nnoremap <leader>4 yypVr-
nnoremap <leader>5 yypVr^
nnoremap <leader>6 yypVr"   

" }}}
" MacVim ---------------------------------------------------------------------- {{{

if has('gui_running')
    set guifont=Anonymous\ Pro:h14   
    set guioptions-=T          	" remove the toolbar
    set lines=96               	" 40 lines of text instead of 24,
    set transparency=5          " Make the window slightly transparent

    " Remove all the UI cruft
    set go-=T
    set go-=l
    set go-=L
    set go-=r
    set go-=R

    " PeepOpen
    if has("gui_macvim")
      map <leader><leader> <Plug>PeepOpen
    end

    highlight SpellBad term=underline gui=undercurl guisp=Orange

    " Use a line-drawing char for pretty vertical splits.
    set fillchars=vert:│

    " Different cursors for different modes.
    set guicursor=n-c:block-Cursor-blinkon0
    set guicursor+=v:block-vCursor-blinkon0
    set guicursor+=i-ci:ver20-iCursor

    " Use the normal HIG movements, except for M-Up/Down
    let macvim_skip_cmd_opt_movement = 1
    no   <D-Left>       <Home>
    no!  <D-Left>       <Home>
    no   <M-Left>       <C-Left>
    no!  <M-Left>       <C-Left>

    no   <D-Right>      <End>
    no!  <D-Right>      <End>
    no   <M-Right>      <C-Right>
    no!  <M-Right>      <C-Right>

    no   <D-Up>         <C-Home>
    ino  <D-Up>         <C-Home>
    imap <M-Up>         <C-o>{

    no   <D-Down>       <C-End>
    ino  <D-Down>       <C-End>
    imap <M-Down>       <C-o>}

    imap <M-BS>         <C-w>
    inoremap <D-BS>     <esc>my0c`y
else
  set term=builtin_ansi       " Make arrow and other keys work
endif

" }}}
